### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by toddlerya** [wybiral/tube#15]
```# xxx @ xxxMacBook-Pro in ~/go/src/github.com/wybiral/tube on git:master o [0:08:30]
$ go run main.go
2019/07/19 00:08:34 dial tcp 127.0.0.1:9051: connect: connection refused
exit status 1
```
-----
help me.

**Comment by wybiral** [comment]
You need to have a Tor daemon running in its current form. It looks like there's no Tor controller at the default port 9051.

**Comment by toddlerya** [comment]
wow, it works. Thank U.

**Comment by KonstantinDjairo** [comment]
same here, but this solution didnt worked, and i already checked if the tor is running on the correct port
